name: Test Deploy

on:
  push:
    branches: [ "dev" ]

jobs:

  deploy:
    runs-on:
      ubuntu-latest
    steps:
      - name: Doing a deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Deploying to the server"
            source /root/.nvm/nvm.sh
            nvm use v20.12.2
            echo "Checking node and npm versions"
            node -v
            npm -v
            cd /var/www/filmvisarna
            git pull
