name: Deploy Workflow

# This workflow will run on every push to the repository in the dev branch.
on:
  push:
    branches:
      - dev

# The jobs to run in this workflow are defined here.
jobs:

  # The deploy job will run on the ubuntu-latest runner and will have the following steps.
  deploy:
  # This job will run only when the cypress_tests job is successful.
    runs-on:
      ubuntu-latest
  # The steps to deploy the application to the server using SSH action.
    steps:
      - name: Doing a deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
            echo "Deploying to the server"
            source /root/.nvm/nvm.sh
            nvm use v20.12.2
            echo "Checking node and npm versions"
            node -v
            npm -v
            cd /srv/www/filmvisarna
            git pull
            rm -r cypress
            npm ci
            npm run build
            pm2 restart react-bio
            
