name: CI Workflow

# This workflow will run on every push to the repository in the dev branch.
on:
  pull_request:
    branches:
      - dev

# The jobs to run in this workflow are defined here.
jobs:

  # The cypress_tests job will run on the ubuntu-latest runner and will have the following steps.
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code using the actions/checkout@v2 action.
      - name: Checkout code
        uses: actions/checkout@v2
    # Setup Node.js using the actions/setup-node@v2 action.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
    # Install dependencies, build and start the server.
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start server
        run: nohup node index.js &
    # Install Cypress dependencies and run the tests.
      - name: Install Cypress Dependencies
      # Change the directory to the cypress folder.
        run: cd ./cypress && npm ci

      - name: Run Cypress tests
      # Change the directory to the cypress folder.
        run: cd ./cypress && npm run test